### ISSUE TITLE
Identify Feature Selectors for Implementation

### ISSUE THREAD

**Issue by dkruszew** [UBC-MDS/feature-selection-python#1]
Identify two feature selectors to code in addition to:

- Forward Selection
- Reverse Selection
- ?
- ?

**Comment by dkruszew** [comment]
Did some research on two feature selectors to choose, focused on these four:

1. Variance Thresholding (Unsupervised Learning)

- Scale all features
- Calculate variance of each feature
- If variance is below a threshold, remove the feature
- LOGIC: Low variance features contain less useful information
- Sklearn: https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.VarianceThreshold.html#sklearn.feature_selection.VarianceThreshold

2. LASSO Linear Regression

- Preform linear regression on features with L1 regularization
- Remove features that have weights of 0
- Sklearn:
https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html

3. Simulated Annealing

-  Randomly choose feature set
- Compute performance
- Modify chosen feature set by randomly excluding 5% of chosen features or including unchosen features
- Recompute performance of slightly modified feature set
- If performance better, use new set, if worse, roll a dice to see if the new set is still kept even if worse, the odds off doing this are reduced as the number of iterations progresses and depending on how bad the new set is compared to the current set.
- More complexity can be added, but this is the gist.
- Documentation: http://www.feat.engineering/simulated-annealing.html

4. Genetic Algorithms

- Randomly select multiple feature sets (say 12)
- Compute the performance of each set
- Define the probability of keeping each set based on its performance
- Roll a dice to see if each set is kept
- For every two sets remaining, merge the sets together as “parents” by exchanging half the chosen features in each to create children.
- Apply randomness by rolling dice with small percentage of success to see if each feature in the children flicks on or off (“mutations”)
- Repeat cycle until one feature set remains
- Documentation: http://www.feat.engineering/genetic-algorithms.html

My recommendation is to do Variance Thresholding, because it is very easy to implement and useful for unsupervised learning data sets, and Simulated Annealing because the implementation also seems relatively simple.

**Comment by jackyho112** [comment]
@dkruszew Thanks for the research and suggestions! I agree with picking variance thresholding and simulated annealing as well!

**Comment by vcuspinera** [comment]
Also it sounds good to me (variance thresholding and simulated annealing)

**Comment by techrah** [comment]
For RFE, current implementations are:

• R: [RFE in caret](https://www.rdocumentation.org/packages/caret/versions/6.0-85/topics/rfe)
• Py: [RFE in scikit](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html)

Do we still want to implement this or pick something else?

**Comment by dkruszew** [comment]
@ryanhomer 

Up to you and the level of work you'd like to take on. I'm ok with any of the below options:

1. Creating wrapper function for RFE
2. Re-write out your own version of RFE for practice/better understanding
3. Some combination of 1&2
4. Switching this function to something like a genetic algorithm

I recommend option 3: writing your own function in R (assuming this is your weaker programming language) for the practice and wrapping scikit RFE in python, but also encourage taking a stab at Genetic Algorithm if you can spare the time.

**Comment by techrah** [comment]
Thanks @dkruszew. I think I will go with your recommendation of #3 and do the R implementation. The caret version seems quite complicated so the motivation will be to have something simpler, more in parity with scikit-learn's implementation for those who want/need something simple on the R side.
