### ISSUE TITLE
Why we chose the MIT license

### ISSUE THREAD

**Issue by jackyho112** [UBC-MDS/feature-selection-python#98]
The MIT license is one of the most common licenses used by open source projects, and we also chose this as our license for many good reasons. 

The first and the most important reason is that we want to be permissive so that the package can be used for any purpose. The MIT license is appropriate for that because it allows commercial and private use with or without modification. It includes no restriction in using the package, and we feel that that is the best way to maximize the value it provides to the community. 

Second, we are providing this in the hopes that others find it useful but we are aware of the financial burdens of litigation. This is why we want to waive the warranty and any liability, which is what the MIT license specifies. 

Third, the license allows us to retain copyright. A lot of work went into the creation of this package, and we feel it essential that everyone who contributed gets credit for his work if it is used in other software packages.

**Comment by vcuspinera** [comment]
Project finished.
